#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
author: FromDarkHell
name: FromDarkHell's Screaming
title: fdh

show_downloads: true
theme: jekyll-theme-hacker

# Short bio or description (displayed in the header)
description: How about those video games am I rite

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars0.githubusercontent.com/u/9018764?s=400&u=fc458ef7c96ec977cd5cc8d4950744bfac63c8f5&v=4

plugins:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-target-blank
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-tailwind

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: FromDarkHell
  instagram:
  linkedin:
  pinterest:
  rss: yes # just type anything here for a working RSS icon
  twitter: FromDarkHell
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: channel/UCwBdQkIk9aAsUEk3Lxrf8fQ # channel/<your_long_string> or user/<user-name>

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://fdh.one

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
markdown: kramdown
highlighter: none
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  hard_wrap: true

  # Disable all of the syntax highlighting
  highlighter: none
  syntax_highlighter: none
  syntax_highlighter_opts:
    disable: true

whitelist:
  - jekyll-redirect-from

# Exclude these files from your production _site
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  - scope:
      path: "_posts/gameInfo"
    values:
      gameInfo: "true"
  - scope:
      path: "_posts/lore-info"
    values:
      loreInfo: "true"

tailwind:
  input: assets/css/app.css
  minify: true # defaults to false
